# Generated by Django 3.1.6 on 2021-02-18 15:10

import Subscriber.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active Subscriber')),
                ('serial_num', models.DecimalField(decimal_places=0, default=Subscriber.models.next_serial_num, max_digits=4, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('num_of_family_member', models.DecimalField(decimal_places=0, help_text="You, your spouse and children if they haven't subscribed", max_digits=2)),
                ('gurdian_type', models.CharField(choices=[('Father', 'Father'), ('Spouse', 'Spouse')], default='Father', max_length=6)),
                ('gurdian_name', models.CharField(max_length=255)),
                ('identity', models.TextField(blank=True, help_text='Relative, Clan or House', null=True)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('nid_num', models.CharField(blank=True, max_length=17, null=True, verbose_name='National Identity Number')),
                ('birth_certificate_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='Birth Certificate Number')),
                ('blood_group', models.CharField(choices=[('N/A', 'N/A'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='N/A', max_length=3)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Married', max_length=9)),
                ('subscription_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('serial_num', 'name'),
            },
        ),
    ]
