# Generated by Django 3.1.6 on 2021-02-21 03:44

import Subscriber.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('serial_num',)},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='birth_certificate_num',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Birth Certificate Number'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='serial_num',
            field=models.DecimalField(decimal_places=0, default=Subscriber.models.next_serial_num, help_text=Subscriber.models.suggest_serial_num, max_digits=4, unique=True),
        ),
    ]
