# Generated by Django 3.1.7 on 2021-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriber', '0002_auto_20210221_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='eidgah_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য ঈদ্গাহের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='graveyeard_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য কবরস্থানের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='mosque_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য মসজিদের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='mustichal_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য মুষ্টি চালের টাকা'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tarabih_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য তারাবীর টাকা'),
        ),
    ]
