# Generated by Django 3.1.7 on 2021-03-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriber', '0004_auto_20210307_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='identity',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Relative, Clan or House', null=True, verbose_name='About subscriber...'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'Ab+'), ('AB-', 'Ab-')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6),
        ),
    ]
