# Generated by Django 3.1.7 on 2021-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriber', '0005_auto_20210307_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-serial_num']},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Relative, Clan or House', null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='birth_certificate_num',
            field=models.CharField(blank=True, help_text='Instead of NID enter Birth Certificate Number. It must be in 17 digit', max_length=17, null=True, verbose_name='Birth Certificate Number'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'Ab+'), ('AB-', 'Ab-')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='nid_num',
            field=models.CharField(blank=True, help_text='National Identity Number must be in 17 digit', max_length=17, null=True, verbose_name='National Identity Number'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(help_text='Phone number must be in 11 digit', max_length=11),
        ),
    ]
