# Generated by Django 3.1.6 on 2021-02-21 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='eidgah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ঈদ্গাহ'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='graveyeard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='কবরস্থান'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='mosque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='মসজিদ'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='mustichal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='মুষ্টি চাল'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='tarabih',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='তারাবীহ'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='year',
            field=models.CharField(default=2021, max_length=4),
        ),
    ]
