# Generated by Django 3.1.6 on 2021-02-21 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriber', '0002_auto_20210221_0944'),
        ('Organization', '0002_auto_20210221_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('Mosque', 'Mosque'), ('Graveyeard', 'Graveyeard'), ('Eidgah', 'Eidgah'), ('Mustichal', 'Mustichal'), ('Tarabih', 'Tarabih')], max_length=10)),
                ('voucher_no', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='year',
            field=models.CharField(default=2021, max_length=4, verbose_name='হিসাব কাল'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionfee',
            unique_together={('subscriber', 'year')},
        ),
    ]
