# Generated by Django 3.1.7 on 2021-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_auto_20210221_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionfee',
            options={'ordering': ('year',)},
        ),
        migrations.RemoveField(
            model_name='subscriptionfee',
            name='eidgah',
        ),
        migrations.RemoveField(
            model_name='subscriptionfee',
            name='graveyeard',
        ),
        migrations.RemoveField(
            model_name='subscriptionfee',
            name='mosque',
        ),
        migrations.RemoveField(
            model_name='subscriptionfee',
            name='mustichal',
        ),
        migrations.RemoveField(
            model_name='subscriptionfee',
            name='tarabih',
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='eidgah_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য ঈদ্গাহের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='eidgah_recovered',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়কৃত ঈদ্গাহের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='graveyeard_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য কবরস্থানের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='graveyeard_recovered',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়কৃত কবরস্থানের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='mosque_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য মসজিদের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='mosque_recovered',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়কৃত মসজিদের বেতন'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='mustichal_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য মুষ্টি চালের টাকা'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='mustichal_recovered',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়কৃত মুষ্টি চালের টাকা'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='tarabih_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়যোগ্য তারাবীর টাকা'),
        ),
        migrations.AddField(
            model_name='subscriptionfee',
            name='tarabih_recovered',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='আদায়কৃত তারাবীর টাকা'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('Mosque', 'Mosque'), ('Graveyeard', 'Graveyeard'), ('Eidgah', 'Eidgah'), ('Tarabih', 'Tarabih')], max_length=10),
        ),
    ]
