# Generated by Django 3.1.7 on 2021-03-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_auto_20210306_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfee',
            name='eidgah_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, default='200', max_digits=10, null=True, verbose_name='আদায়যোগ্য ঈদ্গাহের বেতন'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='graveyeard_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, default='200', max_digits=10, null=True, verbose_name='আদায়যোগ্য কবরস্থানের বেতন'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='mosque_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, default='200', max_digits=10, null=True, verbose_name='আদায়যোগ্য মসজিদের বেতন'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='mustichal_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, default='200', max_digits=10, null=True, verbose_name='আদায়যোগ্য মুষ্টি চালের টাকা'),
        ),
        migrations.AlterField(
            model_name='subscriptionfee',
            name='tarabih_recoverable',
            field=models.DecimalField(blank=True, decimal_places=0, default='200', max_digits=10, null=True, verbose_name='আদায়যোগ্য তারাবীর টাকা'),
        ),
    ]
